In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/uab-the-hack-2024/grupos_cleaned.csv
/kaggle/input/uab-the-hack-2024/caracteristicas.csv
/kaggle/input/uab-the-hack-2024/ubicaciones_cleaned.csv
/kaggle/input/uab-the-hack-2024/calendario_grupos_merged.csv
/kaggle/input/uab-the-hack-2024/franjas_cuarto_hora.csv
/kaggle/input/uab-the-hack-2024/calendario_grupos_clean.csv
/kaggle/input/uab-the-hack-2024/merged_caracteristicas_recursos.csv
/kaggle/input/uab-the-hack-2024/not_merged_caracteristicas_recursos.csv
/kaggle/input/uab-the-hack-2024/recursos_caracteristicas.csv
/kaggle/input/uab-the-hack-2024/calendario_grupos.csv

In [2]:
import pandas as pd

# Load the dataset to examine it
file_path = '/kaggle/input/uab-the-hack-2024/calendario_grupos.csv'
dataset = pd.read_csv(file_path)

# Display the first few rows of the dataset to understand its structure
dataset.columns

Index(['ID_ORIGEN', 'ID_GRUPO', 'ID_FECHA_GRUPO', 'ID_UBICACION',
       'ID_HORA_INICIO', 'ID_HORA_FIN', 'ID_QUART_HORA',
       'IND_HORAS_CALENDARIO', 'ID_SESION', 'ID_CURSO_ACADEMICO',
       'ID_UBICACION_SAMAS', 'IND_PCT_CLAU', 'ID_CENTRE_COST',
       'ID_UNITAT_COST', 'ID_PROJECTE', 'ID_CLAU_ACCES', 'IND_METRES',
       'ID_RESPONSABLE_RESERVA', 'ID_TIPO_RESERVA'],
      dtype='object')

In [8]:
d_filtered = dataset[dataset['ID_UBICACION'].str.contains(r'Q', regex=True, na=False)]
dataset['ID_ORIGEN'].unique()

array(['G', 'P'], dtype=object)

In [89]:
# Dropeamos las columnas que no aportan nada a nuestro problema
dataset = dataset.drop(columns=['ID_ORIGEN', 'IND_HORAS_CALENDARIO', 'IND_PCT_CLAU', 'ID_UNITAT_COST', 'ID_PROJECTE', 'ID_CLAU_ACCES', 'ID_TIPO_RESERVA', 'ID_CENTRE_COST', 'ID_QUART_HORA', 'ID_SESION', 'IND_METRES', 'ID_CURSO_ACADEMICO', 'ID_RESPONSABLE_RESERVA', 'ID_UBICACION_SAMAS', 'ID_UBICACION'])
dataset = dataset[dataset['ID_GRUPO'] != "-1"]
dataset = dataset.drop_duplicates()
dataset

                         ID_GRUPO ID_FECHA_GRUPO  ID_HORA_INICIO  ID_HORA_FIN
6884     2024-0-102-102927-58-633     2025-07-22            1400         1500
16190      2024-0-111-101985-69-1     2025-07-04            1045         1300
16254      2024-0-111-102034-69-1     2025-07-04             930         1300
16258    2024-0-103-102497-69-942     2025-07-04            1700         1945
16269    2024-0-103-100138-69-412     2025-07-04            1700         2000
...                           ...            ...             ...          ...
1047965  2024-0-102-106714-73-773     2024-12-09             900         1300
1047981   2024-0-102-106687-1-102     2024-12-09            1000         1100
1047989     2024-0-111-101642-1-1     2024-12-09             800          900
1047991  2024-0-111-102036-55-413     2024-12-09            1730         1830
1047995    2024-0-108-101148-56-1     2024-12-09            1100         1300

[99785 rows x 4 columns]

In [91]:
csv_file_path = '/kaggle/working/calendario_grupos_clean.csv'
df.to_csv(csv_file_path, index=False)